### ISSUE TITLE
Check postcondition

### ISSUE THREAD

**Issue by mlb0029** [mlb0029/2017PCTR_M109#2]
Definir y comprobar las postcondiciones de los métodos modificadores. Se tiene que utilizar asertos
de Java para modelar el invariante “las bolas no pueden salirse fuera del tablero”

Terminar la implementación de los métodos move() y reflect() de la clase [2017PCTR_M109/src/pg01/Ball.java](https://github.com/mlb0029/2017PCTR_M109/blob/master/src/pg01/Ball.java) añadiendo la comprobación de las postcondición correspondiente.

**Comment by ClaraPalacios** [comment]
Se han creado las poscondiciones para las funciones move y reflect comprobando que no se salgan del tablero.
