### ISSUE TITLE
Actualizar número de bolas

### ISSUE THREAD

**Issue by mlb0029** [mlb0029/2017PCTR_M109#3]
// TODO update with number of group label. See practice statement.
	private final int N_BALL = 2;

Actualizar el valor al número de bolas requerido por el enunciado:
El número de bolas que hay que añadir al tablero debe ser xx + 3, donde xx es el número del grupo
de práctica asignado por el profesor.
Grupo asignado por el profesor: 09

**Comment by ClaraPalacios** [comment]
Hemos actualizado el número de bolas a 12 (9 +3) ya que nuestro grupo es el número 9
